name: GPU • Inspect & Helpers

on:
  workflow_dispatch:
    inputs:
      region_id:
        description: "Region to inspect (default: ewr)"
        required: false
        default: "ewr"
      instance_id:
        description: "Instance ID (optional for inspection)"
        required: false
        default: ""

jobs:
  inspect:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install vultr-cli + jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          # Quick install of vultr-cli via Go (reliable on runners)
          sudo apt-get install -y golang
          export GOPATH="$HOME/go"
          export PATH="$GOPATH/bin:$PATH"
          /usr/bin/env bash -lc 'go install github.com/vultr/vultr-cli/v3@latest'
          vultr-cli version || true

      - name: Check secret
        run: |
          if [ -z "${{ secrets.VULTR_API_KEY }}" ]; then
            echo "::error::Missing secret VULTR_API_KEY"
            exit 1
          fi

      - name: List helpers (regions/os/plans availability)
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
        run: |
          chmod +x scripts/list_helpers.sh
          ./scripts/list_helpers.sh "${{ github.event.inputs.region_id }}" | tee helpers.txt
          echo "### Helpers" >> $GITHUB_STEP_SUMMARY
          echo '**Region:** ${{ github.event.inputs.region_id }}' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat helpers.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Inspect instance (optional)
        if: ${{ inputs.instance_id != '' }}
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
        run: |
          curl -sS -X GET "https://api.vultr.com/v2/instances/${{ inputs.instance_id }}" \
            -H "Authorization: Bearer ${VULTR_API_KEY}" | jq .

